### ISSUE TITLE
index not found

### ISSUE THREAD

**Issue by abhishekrai43** [marella/chatdocs#57]
Not sure what is wrong here. the db and index folders are at their default locations. Even so I copied them to each and evey folder possible. But still it is giving the same error. 
 ```
File "C:\Users\Administrator\Documents\chatdocs\chatdocs\Lib\site-packages\langchain\vectorstores\chroma.py", line 312, in similarity_search_with_score
    results = self.__query_collection(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Documents\chatdocs\chatdocs\Lib\site-packages\langchain\utils\utils.py", line 30, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Documents\chatdocs\chatdocs\Lib\site-packages\langchain\vectorstores\chroma.py", line 145, in __query_collection
    return self._collection.query(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Documents\chatdocs\chatdocs\Lib\site-packages\chromadb\api\models\Collection.py", line 227, in query
    return self._client._query(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Documents\chatdocs\chatdocs\Lib\site-packages\chromadb\api\local.py", line 437, in _query
    uuids, distances = self._db.get_nearest_neighbors(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Documents\chatdocs\chatdocs\Lib\site-packages\chromadb\db\clickhouse.py", line 585, in get_nearest_neighbors
    uuids, distances = index.get_nearest_neighbors(embeddings, n_results, ids)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Documents\chatdocs\chatdocs\Lib\site-packages\chromadb\db\index\hnswlib.py", line 240, in get_nearest_neighbors
    raise NoIndexException(
chromadb.errors.NoIndexException: Index not found, please create an instance before querying
```

**Comment by abhishekrai43** [comment]
load INSTRUCTOR_Transformer
max_seq_length  512
Using embedded DuckDB with persistence: data will be stored in: db
CUDA extension not installed.
The safetensors archive passed at C:\Users\Administrator/.cache\huggingface\hub\models--TheBloke--Llama-2-7b-Chat-GPTQ\snapshots\b7ee6c20ac0bba85a310dc699d6bb4c845811608\gptq_model-4bit-128g.safetensors does not contain metadata. Make sure to save your model with the `save_pretrained` method. Defaulting to 'pt' metadata.
skip module injection for FusedLlamaMLPForQuantizedModel not support integrate without triton yet.
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
 * Serving Quart app 'chatdocs.ui'
 * Environment: production
 * Please use an ASGI server (e.g. Hypercorn) directly in production
 * Debug mode: False
 * Running on http://localhost:5000 (CTRL + C to quit)  this doesn't seem like the ideal output. I am on a windows server using pyton 11. Someone said, 7B models are "lightinig fast" . I am using the following yml
 *embeddings:
  model: hkunlp/instructor-large

llm: gptq

gptq:
  model: TheBloke/Llama-2-7b-Chat-GPTQ
  model_file: C:\Users\Administrator\Downloads\gptq_model-4bit-128g.safetensors
  device: 0
  pipeline_kwargs:
    max_new_tokens: 256

download: false

host: localhost
port: 5000
auth: false

chroma:
  persist_directory: db
  chroma_db_impl: duckdb+parquet
  anonymized_telemetry: false

retriever:
  search_kwargs:
    k: 4  , could you please guide me a little on how to get this "lighting fast" performance out of this? I am on a Tesla T4 AWS EC-2. If there is no other option than to move to linux, I will do that as well, but it will increase my work manyfold, so tell me if there is a way to get this done on the same machine please.

**Comment by vmirea** [comment]
Got the same error:
  File "/media/vmirea/NTFS_8TB/projects/chatdocs/venv/lib/python3.11/site-packages/chromadb/db/index/hnswlib.py", line 240, in get_nearest_neighbors
    raise NoIndexException(
chromadb.errors.NoIndexException: Index not found, please create an instance before querying

(venv) (base) vmirea@vmirea-Z390-GAMING-SLI:/media/vmirea/NTFS_8TB/projects/chatdocs$ chatdocs ui
load INSTRUCTOR_Transformer
max_seq_length  512
Using embedded DuckDB with persistence: data will be stored in: db
 * Serving Quart app 'chatdocs.ui'
 * Environment: production
 * Please use an ASGI server (e.g. Hypercorn) directly in production
 * Debug mode: False
 * Running on http://localhost:5000 (CTRL + C to quit)
[2023-10-31 11:46:08 +0000] [1644470] [INFO] Running on http://127.0.0.1:5000 (CTRL + C to quit)
[2023-10-31 11:46:29 +0000] [1644470] [INFO] 127.0.0.1:55924 GET / 1.1 200 4416 10527
[2023-10-31 11:46:29 +0000] [1644470] [INFO] 127.0.0.1:55924 GET / 1.1 - - 11205
[2023-10-31 11:46:29 +0000] [1644470] [INFO] 127.0.0.1:55932 GET /ws 1.1 101 - 510
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "/home/vmirea/miniconda3/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/vmirea/miniconda3/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/media/vmirea/NTFS_8TB/projects/chatdocs/venv/lib/python3.11/site-packages/chatdocs/ui.py", line 33, in worker
    res = qa(query)
          ^^^^^^^^^
  File "/media/vmirea/NTFS_8TB/projects/chatdocs/venv/lib/python3.11/site-packages/langchain/chains/base.py", line 310, in __call__
    raise e
  File "/media/vmirea/NTFS_8TB/projects/chatdocs/venv/lib/python3.11/site-packages/langchain/chains/base.py", line 304, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/media/vmirea/NTFS_8TB/projects/chatdocs/venv/lib/python3.11/site-packages/langchain/chains/retrieval_qa/base.py", line 136, in _call
    docs = self._get_docs(question, run_manager=_run_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/vmirea/NTFS_8TB/projects/chatdocs/venv/lib/python3.11/site-packages/langchain/chains/retrieval_qa/base.py", line 216, in _get_docs
    return self.retriever.get_relevant_documents(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/vmirea/NTFS_8TB/projects/chatdocs/venv/lib/python3.11/site-packages/langchain/schema/retriever.py", line 211, in get_relevant_documents
    raise e
  File "/media/vmirea/NTFS_8TB/projects/chatdocs/venv/lib/python3.11/site-packages/langchain/schema/retriever.py", line 204, in get_relevant_documents
    result = self._get_relevant_documents(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/vmirea/NTFS_8TB/projects/chatdocs/venv/lib/python3.11/site-packages/langchain/schema/vectorstore.py", line 657, in _get_relevant_documents
    docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/vmirea/NTFS_8TB/projects/chatdocs/venv/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 261, in similarity_search
    docs_and_scores = self.similarity_search_with_score(query, k, filter=filter)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/vmirea/NTFS_8TB/projects/chatdocs/venv/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 346, in similarity_search_with_score
    results = self.__query_collection(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/vmirea/NTFS_8TB/projects/chatdocs/venv/lib/python3.11/site-packages/langchain/utils/utils.py", line 35, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/media/vmirea/NTFS_8TB/projects/chatdocs/venv/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 156, in __query_collection
    return self._collection.query(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/vmirea/NTFS_8TB/projects/chatdocs/venv/lib/python3.11/site-packages/chromadb/api/models/Collection.py", line 227, in query
    return self._client._query(
           ^^^^^^^^^^^^^^^^^^^^
  File "/media/vmirea/NTFS_8TB/projects/chatdocs/venv/lib/python3.11/site-packages/chromadb/api/local.py", line 437, in _query
    uuids, distances = self._db.get_nearest_neighbors(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/vmirea/NTFS_8TB/projects/chatdocs/venv/lib/python3.11/site-packages/chromadb/db/clickhouse.py", line 585, in get_nearest_neighbors
    uuids, distances = index.get_nearest_neighbors(embeddings, n_results, ids)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/vmirea/NTFS_8TB/projects/chatdocs/venv/lib/python3.11/site-packages/chromadb/db/index/hnswlib.py", line 240, in get_nearest_neighbors
    raise NoIndexException(
chromadb.errors.NoIndexException: Index not found, please create an instance before querying
